name: Ubuntu 22.04 Iron Build

on:
  pull_request:
  push:
    branches:
      - iron
  schedule:
    # At 5:10 each day
    - cron:  '10 05 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    timeout-minutes: 10
    runs-on: self-hosted
    container:
      image: osrf/ros:iron-desktop-full-jammy

    steps:
    - name: Update
      run: apt-get update

    - name: Install PIP
      run: apt-get install -y python3-pip lcov

    - name: Install colcon tools
      run: python3 -m pip install colcon-lcov-result colcon-coveragepy-result

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.6
      with:
        target-ros2-distro: iron
        import-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
      if: failure()
