name: Ubuntu 22.04 Jazzy Build

on:
  pull_request:
  push:
    branches:
      - iron
  schedule:
    # At 5:10 each day
    - cron:  '10 05 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    timeout-minutes: 10
    runs-on: self-hosted
    container:
      image: ${{ vars.LOCAL_DOCKER_REGISTRY_IP }}:5000/roxy_jazzy:base

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.16
      with:
        target-ros2-distro: jazzy
        skip-rosdep-install: true